openapi: 3.0.0

info:
  title: ShoppShop OpenAPI
  version: 0.0.1
  contact:
    name: Vova Revenko
    email: vova@revenko.org
    url: https://github.com/vovarevenko

components:
  schemas:
    $ref: './schemas/_index.yml'

paths:
  /users:
    get:
      operationId: getUsers
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
